### ISSUE TITLE
Optional progressbar end frame

### ISSUE THREAD

**Issue by ptheywood** [matze/mtheme#126]
I'm currently working on a presentation for a conference, and plan on adding additional frames including extra figures / tables to support answering questions which may crop up depending on the audience. 
These additional slides (and slides containing references) causes the progress bar to be misleading - I would like it to show my designated final slide as the 100% complete progress bar.

I have found a workaround on Stack Overflow for manipulating the maximum slide number which has the desired effect (http://tex.stackexchange.com/a/2559)

I would like to know if you feel like this would be a useful featuer for integration with the theme in a user friendly way such as an additional (optional) command to set the end frame for the progress bar (i.e `\progressbarlimit`)?

If so I would be willing to (attempt) to implement this, or if not I'll just continue to use the workaround.

**Comment by matze** [comment]
> I would like to know if you feel like this would be a useful featuer for integration with the theme in a user friendly way such as an additional (optional) command to set the end frame for the progress bar (i.e \progressbarlimit)?

Definitely! In my experience "backup slides" are a pretty common thing, so that would be a very useful addition.

**Comment by Ezibenroc** [comment]
+1 for this addition, I was going to open a similar issue. Thank you for the workaround.

**Comment by rchurchley** [comment]
Thanks for bringing this up! I learned a thing or two from the answers on that StackExchange question. It looks like there are at least two easy solutions for adding backup slides:

1. Use `\appendix` and the `appendixnumberbeamer` package to divide the presentation into two independently-numbered parts. If you have 20 regular slides and 10 backup slides, the last regular slide will be numbered 20/20 and have a full progress bar, while the first backup slide will read 1/10 and have a nearly-empty progress bar.
    ```
    \usepackage{appendixnumberbeamer}
    ...
    \appendix
    \begin{frame}{First backup slide} ... \end{frame}
    \begin{frame}{Second backup slide} ... \end{frame}
    ```
    As far as I can tell, this works perfectly with Metropolis.

2. Add the `noframenumbering` optional argument to each backup frame. If you have 20 regular slides and 10 backup slides, the last regular slide and all backup slides will be numbered 20/20 and have a full progress bar.
    ```
    \begin{frame}[noframenumbering]{First backup slide} ... \end{frame}
    \begin{frame}[noframenumbering]{Second backup slide} ... \end{frame}
    ```
    This solution just about works under Metropolis. However, there is a problem if your backup slides contain a `\plain` slide or a `section page`: those add frames without giving the user the option to specify `noframenumbering`. Arguably, those content-light slides shouldn't count towards the numbering anyways, so perhaps we should change them to be `noframenumbering` by default?

Since these existing techniques look pretty good and easy-to-use, I don't think we need to duplicate them with new commands. However, I think it would be a great idea to add some backup slides to the demo presentation to show that these solutions work in Metropolis!
