### ISSUE TITLE
Cannot find fira fonts

### ISSUE THREAD

**Issue by bklamer** [matze/mtheme#152]
The change to conditional font detection has broken metropolis for my installation. I am on ubuntu 14.04 with TexLive 2015 and have fira v4.1 installed. When compiling with lualatex, I receive a warning that the fira fonts cannot be found and they are not used in the resulting pdf. It worked fine with the previous font methods.

**Comment by benjamin-weiss** [comment]
Without checking I just assumed the font handling would work exactly the same for XeLaTeX and LuaTeX. But I can reproduce your problem with LuaTex. So there must be some difference. But as of now I still couldn't figure out what the actual problem is. 

As a workaround until it is fixed you can load the fira font manually after you loaded the theme.
```TeX
\documentclass{beamer}
\usetheme{metropolis}
\setsansfont[BoldFont={Fira Sans}]{Fira Sans Light}
\setmonofont{Fira Mono}
\begin{document}
\begin{frame}{Title}
	Content
\end{frame}
\end{document}
```

**Comment by benjamin-weiss** [comment]
Can you please check if [this patch](https://github.com/benjamin-weiss/mtheme/tree/font-loading-fix) fixes your problem?

**Comment by bklamer** [comment]
Yes, it compiles normally again. thanks
