### ISSUE TITLE
Cannot compile demo.tex using CTAN beamertheme-metropolis

### ISSUE THREAD

**Issue by danjjl** [matze/mtheme#164]
Using the CTAN version (39020) of metropolis I cannot compile demo.tex

    ! Package pgfkeys Error: I do not know the key '/titleformat frame', to which you passed 'smallcaps', and I am going to ignore it. Perhaps you misspelled it.
    
    See the pgfkeys package documentation for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                      
    l.68 \metroset{titleformat frame=smallcaps}

**Comment by benjamin-weiss** [comment]
Are you sure you are using the CTAN version? Because the `demo.tex` compiles fine for me with the CTAN version.

Do you have an old version of the theme in your texmf home folder? Because LaTeX will always favor the version in your texmf home folder. So please check that. For example by adding `\listfiles` to a minimal example
```TeX
\listfiles
\documentclass{beamer}
\usetheme{metropolis}
\begin{document}
\frame{Test}
\end{document}
```
and checking the date of the metropolis beamer theme. This is how the log file entry looks like for the CTAN version.
```
Package: beamerthememetropolis 2015/12/04 Metropolis Beamer theme
```

**Comment by jwhendy** [comment]
I just spent a good amount of time trying to resolve my confusion around font formats to see there was a long [issues thread](https://github.com/matze/mtheme/issues/138) surrounding that very topic! In excitement, I also noticed it appeared to be fixed/incorporated, do I did a fresh `git pull` and checked the updated documentation to see how to go about it. After that, I got a bunch of errors with `xelatex` on my previously-working document!

I decided to compile the demo in case it had a clue to my issue, and I couldn't due to many errors like the OP's. I stumble over here and see that I should be using the CTAN version, even though the CTAN version's docs point to this repo as the "latest development version." Indeed, with a pull just a bit ago, I show (thanks for the example of this function, btw!):
```
beamerouterthememetropolis.sty    2015/06/12 Metropolis outer theme
beamercolorthememetropolis.sty    2015/06/12 Metropolis color theme
beamerfontthememetropolis.sty    2015/10/24 Metropolis font theme
```

After replacing with the CTAN version, I get:
```
beamerouterthememetropolis.sty    2015/12/04 Metropolis outer theme
beamercolorthememetropolis.sty    2015/12/04 Metropolis color theme
beamerfontthememetropolis.sty    2015/12/04 Metropolis font theme
```

Would you kindly point to CTAN from the `readme.md` of this site and let people know it's outdated, or (my preference) merge this with the CTAN version (and keep them that way)? I think using features here that are ahead of the actual `.sty` file code is a confusion/hassle.

Thanks for a great theme!

**Comment by benjamin-weiss** [comment]
Except for some minor changes in the documentation the current master is exactly the same as the CTAN version. So you must have done something wrong when you tried to update the theme from github.

But you are right, the current master and the CTAN version should be the same at all time to prevent confusion. So for further commits I think @matze should add a developer branch (as I already proposed earlier).

And some final words about the title formats: Right before the CTAN release we made some changes, that are not backwards compatible. It was to be expected, that this will lead to confusion (so sorry about that), but I still think it was the right thing to do, as we now have a solution we can stick with.

**Comment by matze** [comment]
> But you are right, the current master and the CTAN version should be the same at all time to prevent confusion. So for further commits I think @matze should add a developer branch (as I already proposed earlier).

In my opinion this is the wrong approach and `master` should reflect the current state<sup>1</sup>.
Most open source projects do it the same way and use `master` for development and specific tags/branches for [releases](https://github.com/matze/mtheme/releases).

<sup>1</sup> Aside: I find it extremely annoying if I go to a repo and somehow have to find out that I need to switch branches in order to see what's currently cooking.

**Comment by benjamin-weiss** [comment]
Ok, that's a matter of taste. I kind of like the branching model proposed [here](http://nvie.com/posts/a-successful-git-branching-model/). The whole model is definitely overkill for our purpose, but I like the idea that master should "always reflect a production-ready state".

**Comment by benjamin-weiss** [comment]
Back on topic: Maybe we should add another notice to the `README.md` file to point out that the titleformat options changed with the release of version 1.0

**Comment by matze** [comment]
> I kind of like the branching model proposed here.

I know this and where you're coming from ;-) but my point stands and was probably better verbalized by [this guy](http://endoflineblog.com/gitflow-considered-harmful).

> Back on topic: Maybe we should add another notice to the README.md file to point out that the titleformat options changed with the release of version 1.0

Will do so!

**Comment by benjamin-weiss** [comment]
> was probably better verbalized by this guy

Interesting read. Thank you for that. I have to think about it some more, but he definitely makes some valid points.

**Comment by jwhendy** [comment]
Aaaahhh! Shame me to no end. I'm not used to having to compile a beamer theme, and as soon as I read your comment that they should be identical, the horror set in. Sincere apologies, and after running `make` in my original git version of the theme (that was showing `2015/06/12`), now it's showing `2015/12/04'.

I love the new `titleformat` options, and now have exactly what I was looking for.

For what it's worth, maybe the `readme` could contain the version? Maybe it's common knowledge, but I had no idea how to check a package's version prior to seeing the `\listfiles` command above. In this way, if someone reads the rendered `readme` here and the top says "v1.0" or what have you, they could easily compare with their local version. Maybe the note could also mention that any version-less `readme` means `< 1.0` ? Just one thought.

Thanks so much, and I've eaten my humble pie for the day (hopefully)!

**Comment by benjamin-weiss** [comment]
> For what it's worth, maybe the readme could contain the version?

We just started versioning with the CTAN release and the documentation already contains the version number. (In case you don't know on Linux and Mac OS you can easily open the documentation from the command line with `texdoc metropolis`.) So that's the fast way I usually use to check the version of a package. But for me it makes sense to also add the version number to the readme. @matze?

**Comment by danjjl** [comment]
Oups had forgotten I had filed this issue.
@benjamin-weiss you were right, silly mistake, I had an old version of metropolis in my `texmf` folder.

**Comment by kprav33n** [comment]
I had the same issue on macOS Sierra using MacTex 2016. I was not sure where the old metropolis files were coming from. I'd to run `kpsewhich -var-value=TEXMFHOME` to figure out my local `texmf` directory. In my case, it was `/Users/praveek6/Library/texmf`. After I deleted old versions of metropolis files from there, I'm able to use the new version from MacTex properly.
