### ISSUE TITLE
Frametitle size with parentheses

### ISSUE THREAD

**Issue by danjjl** [matze/mtheme#165]
The vertical size of the frametitle is bigger for titles with parentheses than for titles without.

MWE:

    \documentclass{beamer}
    \usetheme{metropolis}
    \begin{document}

      \begin{frame}{Title with (parentheses)}
      \end{frame}

      \begin{frame}{Title without parentheses}
      \end{frame}
    \end{document}

![screenshot from 2015-12-14 23-53-11](https://cloud.githubusercontent.com/assets/747240/11796697/e7fa1ca0-a2bd-11e5-8928-3fca9ec86b54.png)

This issue looks a lot like https://github.com/matze/mtheme/issues/131.

**Comment by benjamin-weiss** [comment]
You are right this is basically the same problem as #131.

This problem seems to be never-ending with the current implementation using `sep=...`. Maybe the original implementation using `ht=..., dp=..., leftskip=..., rightskip=...` wasn't so bad after all. And simply adjusting `ht=...` and `dp=...` depending on the frame title format should fix #99, too. The only problem I see is, that it will break the support for multiline frame titles again.

**Comment by rchurchley** [comment]
Actually, I think this is the same as #33. The minimum height of the frametitle is set (via struts) to be the maximum height of an alphabetic character. This does not account for the fact that punctuation can be larger than alphabetic characters under `allsmallcaps`.

This issue should be added to the list of unexpected behaviours caused by `allsmallcaps` (as discussed in #138) and can be mitigated by changing the default to `regular` or `smallcaps` (also discussed there).

**Comment by benjamin-weiss** [comment]
@rchurchley I thought about it some more. What do you think about that. We define our strut (in my example for the `regular` case) like that:
```TeX
\renewcommand{\@metropolis@frametitlestrut}{%
  \newdimen\heightOfA
  \setbox0=\hbox{A}
  \heightOfA=\ht0 \advance\heightOfA by \dp0
  \vphantom{\rule[-1.5ex]{1pt}{3ex+\heightOfA}}%
}
```
And change our frame title box definition to this.
```TeX
\begin{beamercolorbox}[%
    wd=\paperwidth,%
    sep=0pt,%
    leftskip=1.5ex,%
    rightskip=1.5ex,%
  ]{frametitle}%
```
Then an **A** is perfectly vertically centered inside the box and every other character will just use the free space above or below, if it needs it.

**Comment by benjamin-weiss** [comment]
@rchurchley Have closer look at @danjjl's example again. The problem has nothing to do with `allsmallcaps`. It also happens for `regular` and `smallcaps`.

**Comment by rchurchley** [comment]
@benjamin-weiss I stand corrected! I haven't been able to test your proposed code yet, but I'd be in favour of it provided it looks nice with multiline titles. Otherwise, as a quick fix for now, adding parentheses to the current definition of the frametitle struts should also solve @danjjl's problem:
```latex
\renewcommand{\@metropolis@frametitlestrut}{%
    \vphantom{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz()}%
}
```

**Comment by benjamin-weiss** [comment]
> provided it looks nice with multiline titles.

Actually it does not (yet). It results in a very big line spacing.

**Comment by benjamin-weiss** [comment]
Fixing the line spacing was also not that hard. If we define two different struts for the beginning and the end, also multiline titles look just fine. You can have a look at the implementation [here](https://github.com/benjamin-weiss/mtheme/tree/new-frametitle-struts).

**Comment by rchurchley** [comment]
Finally got a chance to test this and it seems to work! I'm not particularly satisfied with using struts to create padding --- I'd much prefer using `sep` for the padding and using struts or `\vphantom` to ensure a consistent line height --- but after much thought I can't think of any other solution that
 
- perfectly centres an unadorned `allsmallcaps` frame title,
- maintains a consistent height for all frame titles assuming the `titleformat` is not changed, and
- maintains a consistent baseline for `allsmallcaps` frame titles with punctuation.

(Note that changing the `titleformat` will change the height of the frametitle, but this shouldn't be an issue in real-world presentations.)

Assuming your branch is up-to-date, I think this can be made into a pull request. :+1:

**Comment by benjamin-weiss** [comment]
> Finally got a chance to test this and it seems to work! I'm not particularly satisfied with using struts to create padding --- I'd much prefer using sep for the padding and using struts or \vphantom to ensure a consistent line height

Actually me too. But I also cannot think about any other solution that works how I expect it to.
