### ISSUE TITLE
Minimal Example should clearly mention necessity of using XeLaTeX or LuaTeX

### ISSUE THREAD

**Issue by ChipmunkMath** [matze/mtheme#169]
I think the minimal example in the [manual](http://mirrors.ctan.org/macros/latex/contrib/beamer-contrib/themes/metropolis/doc/metropolistheme.pdf) (section **2.4**) should mention the necessity of running that code with either XeLaTeX or LuaTeX explicitly. As it's currently phrased, I think it's easy to assume that copy-pasting that into a TeX frontend and hitting typeset will spit out the minimal example. Especially easy considering that in the below dependencies section (**2.5**), TikZ and the fonts just need to be properly installed, not "actively used". The typesetting engine has to be actively set by the user -- which they may not be aware of since pdftex is a common default that may have long worked before -- and that happens outside the minimal example code.

On the other hand, this might not be necessary, because the error log will likely be clear that they need to switch the typesetting engine. Still, I think it's an easy addition to the manual that would be helpful for new TeX users.

Here's a possible phrasing to be inserted after the code for the minimal example:

> Make sure to typeset the above using either the XeLaTeX or LuaTex engines (usually a setting in your TeX editor). Alternatively, you can add this as the first line of your document to tell the compiler which engine to use: `%!TEX program = xelatex`

**Comment by matze** [comment]
> I think the minimal example in the manual (section 2.4) should mention the necessity of running that code with either XeLaTeX or LuaTeX explicitly. [...]
> the fonts just need to be properly installed [...]

This is not true though. For a while now, presentations can be typeset with pdfLaTeX that then falls back to (I think) lmodern.

**Comment by ChipmunkMath** [comment]
> This is not true though. For a while now, presentations can be typeset with pdfLaTeX that then falls back to (I think) lmodern.

Hmmm, that's not what I'm seeing on my machine. Running MacTeX 2015, fully updated via TeX Live Utility and using TeXShop as the frontend, I get the following error if I attempt to compile via `LaTeX` from typesetting dropdown:

>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
/usr/local/texlive/2015/texmf-dist/tex/latex/fontspec/fontspec.sty:43: Fatal fo
ntspec error: "cannot-use-pdftex"
! 
! The fontspec package requires either XeTeX or LuaTeX to function.
! 
! You must change your typesetting engine to, e.g., "xelatex" or "lualatex"
! instead of plain "latex" or "pdflatex".
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

I get an identical error if I attempt to compile via `pdflatexmk` in dropdown. On the other hand, choosing `XeLaTeX` and compiling works without any issues. The code I'm trying to compile is just the minimal example:
>\documentclass{beamer}
\usetheme{metropolis} % Use metropolis theme
\title{A minimal example}
\date{\today}
\author{Matthias Vogelgesang}
\institute{Centre for Modern Beamer Themes}
\begin{document}
\maketitle
\section{First Section}
\begin{frame}{First Frame}
Hello, world!
\end{frame}
\end{document}

**Comment by benjamin-weiss** [comment]
As already mentioned in #75 you should check which version of the theme you are actually using. Please check your texmf folder for an old version. Or add a `\listfiles` to your MWE. The CTAN version should show up in the log file like this:

```
Package: beamerthememetropolis 2015/12/04 Metropolis Beamer theme
```

**Comment by ChipmunkMath** [comment]
Currently responding to #75 as well, but yes, I believe am up to date. I get the following in the log when compiling:
> Package: beamerfontthememetropolis 
beamerthememetropolis.sty    2015/12/04 Metropolis Beamer theme
beamerinnerthememetropolis.sty    2015/12/04 Metropolis inner theme
beamerouterthememetropolis.sty    2015/12/04 Metropolis outer theme
beamercolorthememetropolis.sty    
beamerfontthememetropolis.sty

**Comment by rchurchley** [comment]
> /usr/local/texlive/2015/texmf-dist/tex/latex/fontspec/fontspec.sty:43: Fatal fontspec error: "cannot-use-pdftex"
! 
! The fontspec package requires either XeTeX or LuaTeX to function.

The error message you reported *shouldn't* be possible for a new user to get: all versions of the font them since d2e03dc (in October) only load `fontspec` under XeTeX or LuaLaTeX. However, I can think of one way that longtime users like you could run into this.

If you installed a version of Metropolis before the name change and the v1.0 release, then you may have old versions of the following files in an `mtheme` folder still in your TeX path:
```
beamerthemem.sty 
beamerfontthememetropolis.sty
beamerinnerthememetropolis.sty   (if you installed it after June 17)
beamerouterthememetropolis.sty   (if you installed it after June 17)
```
The error you're seeing could be explained if you installed what was then called the `mtheme` sometime before June 17 (b1132a09), and then installed the CTAN package `beamertheme-metropolis` when it was released.

When you try to run the minimal example, `\usetheme{metropolis}` correctly finds the up-to-date version of the package `beamerthememetropolis.sty` — it passes over the old `beamerthemem.sty `, since that has a different name. If your old version of the `mtheme` was installed before June 17, you also don't have conflicting versions of `beamerinnerthememetropolis.sty` and `beamerouterthememetropolis.sty`, so those are found correctly as well. But when it comes to finding `beamerfontthememetropolis.sty`, there are two files in your TeX path with that name: the old version in the `mtheme` folder, and the new version installed tlmgr. Since user-installed packages take precedence over tlmgr-installed packages, you end up loading the old, pdfLaTeX-incompatible version of the font theme, even though all the other packages report as being up-to-date!

To check whether this is actually the case, try running the following from the command line:

```
kpsewhich beamerthememetropolis.sty
kpsewhich beamerfontthememetropolis.sty
```

If things are working correctly, they should both report paths like `/usr/local/texlive/2015/texmf-dist/tex/latex/beamertheme-metropolis/beamerthememetropolis.sty`. If an old version of the font theme is getting in the way, the second one may return something like ``/Users/ChipmunkMath/Library/texmf/tex/latex/mtheme/beamerfontthememetropolis.sty`. If so, then deleting that file (or better, the entire `mtheme` folder at that location) will fix things for you.

Please let us know if this works!

**Comment by matze** [comment]
I'll close this then.

@rchurchley: thanks for the detailed investigation. It will sure help tracking down similar problems in the future.
