### ISSUE TITLE
Horizontal mbarplot stacked

### ISSUE THREAD

**Issue by alcarazr** [matze/mtheme#171]
Why is it that the style for the horizontal mbarplot is stacked by default, while the (vertical) mbarplot not? Is this something the user can easily change?

Thank you very much,

Rodrigo

**Comment by benjamin-weiss** [comment]
You are right. That is a bit weird. Unfortunately you cannot simply overwrite the `xbar stacked` with `xbar` like this:
```TeX
\pgfplotsset{
  horizontal mbarplot/.append style={
    xbar,
  }
}
```
So the easiest way to get a non stacked version is probably to define a new style.
```TeX
\pgfplotsset{
  horizontal notstacked mbarplot/.style={
    mbarplot base,
    xmajorgrids=true,
    ymajorgrids=false,
    xbar,
    area legend,
    legend image code/.code={%
      \draw[#1] (0cm,-0.1cm) rectangle (0.15cm,0.1cm);
    },
    cycle list name=mbarplot cycle,
  },
}
```
The same is true for the other way round. If you want a vertical stacked mbarplot just define a new style.
```TeX
\pgfplotsset{
  stacked mbarplot/.style={
    mbarplot base,
    ybar stacked,
    xmajorgrids=false,
    ymajorgrids=true,
    area legend,
    legend image code/.code={%
      \draw[#1] (0cm,-0.1cm) rectangle (0.15cm,0.1cm);
    },
    cycle list name=mbarplot cycle,
  },
}
```

**Comment by alcarazr** [comment]
Thanks a lot! I am a total newb in pgfplots and was not sure how to modify it without breaking anything.

**Comment by alcarazr** [comment]
Related to this but not really an issue (actually due to my ignorance about pfgplots).

If I plot some data (several curves) with error bars with the mlineplot style, the color of the error bars matches that of the marks and lines. If I plot the data with the mbarplot style, however, the error bars have a different color (only the horizontal lines). I guess this has to do with the custom cycle list definition but have not figured out what exactly is the problema (no marks in the mbarplot?).

Thank you very much in advance,

Rodrigo

PD: is there any way to ask questions without opening a new issue? Thanks!

**Comment by benjamin-weiss** [comment]
For the time being you can define your own cycle list
```TeX
\pgfplotscreateplotcyclelist{my mbarplot cycle}{%
  {TolDarkBlue,    fill=TolDarkBlue!70},
  {TolLightBrown,  fill=TolLightBrown!70},
  {TolLightGreen,  fill=TolLightGreen!70},
  {TolDarkPink,    fill=TolDarkPink!70},
  {TolDarkPurple,  fill=TolDarkPurple!70},
  {TolDarkRed,     fill=TolDarkRed!70},
  {TolDarkBrown,   fill=TolDarkBrown!70},
  {TolLightRed,    fill=TolLightRed!70},
  {TolLightPink,   fill=TolLightPink!70},
  {TolLightPurple, fill=TolLightPurple!70},
  {TolLightBlue,   fill=TolLightBlue!70},
  {TolDarkGreen,   fill=TolDarkGreen!70},
}
```
and use it instead of the original definition.
```TeX
\begin{axis}[mbarplot, cycle list name=my mbarplot cycle] ...
```
No there is no other way to ask questions. Just keep opening new issues if you have any problems.

For the future: It would be really helpful if you would be so kind and prepare a MWE if you have a problem/question. This would make it really easier/faster to help you.

@matze Maybe we should have a second look at `pgfplotsthemetol`. There seems to be room for improvement. Also there is a new pgfplots version with some interesting new ways to combine cycle list.

**Comment by matze** [comment]
> Maybe we should have a second look at pgfplotsthemetol. There seems to be room for improvement. 

Definitely. One of the first things I would change is to (similar to Beamer) split off the structural appearance of plots (i.e. grid lines, ticks, etc.) from colors. By the way, I'd also not hesitate changing the plot styles as I don't consider them as mature and first-class as the actual theme itself.

> Also there is a new pgfplots version with some interesting new ways to combine cycle list.

However, that requires *very* careful planning or at least a way to determine (not setting) the pgfplots compatibility level. Case in point: I often have problems sharing documents with a colleague because he lags several versions of pgfplots behind me.

**Comment by alcarazr** [comment]
Thank you very much, that did the trick. Regarding the MWE, I was thinking about it as I was writing my question. I will surely include one next time.

Thanks for your time,

Rodrigo

**Comment by matze** [comment]
I will close this issue then. Subsequent discussion of theme restructuring can be followed in #178.
