### ISSUE TITLE
Colored footer with solarized

### ISSUE THREAD

**Issue by matze** [matze/mtheme#179]
I have been checking out the [solarized](https://github.com/jrnold/beamercolorthemesolarized) color theme and noticed that the footer is colored a bit differently and sticks out like a sore thumb:

![metropolis-bug](https://cloud.githubusercontent.com/assets/115270/13219285/518ccc02-d96f-11e5-9d38-b63d27b7aaa5.png)

**Comment by rchurchley** [comment]
This appears to be a design choice of the Solarized Beamer color theme rather than a bug in Metropolis. Solarized explicitly sets the colour of the footline [here](https://github.com/jrnold/beamercolorthemesolarized/blob/master/beamercolorthemesolarized.sty#L111):

```latex
\setbeamercolor{footline}{bg=solarizedRebase02,fg=solarizedRebase01}
```

The only way around this, from Metropolis' point of view, would be to move the page number to a beamer template other than `footline`, but I don't know of an appropriate template whose colour wouldn't be changed by other color themes. Users who dislike this colour choice can either remove the page number using the `numbering=none` option, or manually remove the footline colour by adding the following to their preamble:
```latex
\setbeamercolor{footline}{bg=}
```

I don't think this is something Metropolis can (or should) fix; the best we can do is to ensure Metropolis uses the correct colours as defined by other colour themes. It might not always lead to the most visually pleasing result, but since each color theme will require different improvements, it's probably best left to the user to make them.

**Comment by matze** [comment]
>  It might not always lead to the most visually pleasing result, but since each color theme will require different improvements, it's probably best left to the user to make them.

Good point!

**Comment by benjamin-weiss** [comment]
Maybe using `\setbeamercolor{page number in head/foot}{•}` instead of `\setbeamercolor{footline}{•}` makes sense. For the page number the background is usually not set and `footline` is afaik not used in most themes. So it would probably increase the compatibility to most of the other color themes.
