### ISSUE TITLE
Default color theme

### ISSUE THREAD

**Issue by alcarazr** [matze/mtheme#208]
Hi,

I am loving `mtheme` and here I would like to express my gratitude for all the work put on it. Just a comment regarding the default color theme. It seems that the default `orange` and `green` used for `alerted` and `example` text, respectively, do not pass the contrast test according to the [WCAG Guidelines](http://www.w3.org/TR/WCAG20/#visual-audio-contrast), when the background is either the default `black!2` or pure `white` (as [in the documentation](http://osl.ugr.es/CTAN/macros/latex/contrib/beamer-contrib/themes/metropolis/doc/metropolistheme.pdf) for example).

The project [Colorable](http://jxnblk.com/colorable/) (demo [here](http://jxnblk.com/colorable/demos/text/?background=%23fafafa&foreground=%23EB811B)) allows for getting contrast values for every possible combination and includes pass/fail scores according to the [WCAG](http://www.w3.org/TR/WCAG20/#visual-audio-contrast). A safe color combination should have **Level AAA**. As you can check with the [Colorable demo](http://jxnblk.com/colorable/demos/text/?background=%23fafafa&foreground=%23EB811B), when using the _light_ color theme, the `alerted`and `example`colors fail, whereas they have a greater contrast (but still not AAA) when using the _dark_ theme.

Of course the user can change these colors, but I think it would be nice if the default color theme used a _safer_ color combination. Is this something worth considering?

Thanks,

Rodrigo

**Comment by matze** [comment]
First of all: thanks for bringing up that topic. I agree with you that we have to do something about it. I also thought the orange link color in the docs look a bit odd probably caused by this issue.

> It seems that the default orange and green used for alerted and example text, respectively, do not pass the contrast test according to the WCAG Guidelines, when the background is either the default black!2 or pure white (as in the documentation for example).

As far as I can see, it is impossible to have good contrast with that particular orange-to-reddish color on any kind of background (one can see this nicely in the matrix where there is a similar color). However, with 100% saturation and slightly less lightness we can get the orange at least to AA Large (3.19). Lowering lightness further to achieve AAA destroys the color for me though.

> Is this something worth considering?

Yes, definitely. But I think the final decision should not only be driven by quantitative numbers but also on our idea of the design and previous feedback concerning this issue. Going by numbers alone, the whole world would be pitch black on pure white ;-)

**Comment by alcarazr** [comment]
> As far as I can see, it is impossible to have good contrast with that particular orange-to-reddish color on any kind of background (one can see this nicely in the matrix where there is a similar color). However, with 100% saturation and slightly less lightness we can get the orange at least to AA Large (3.19). Lowering lightness further to achieve AAA destroys the color for me though.

Level AA Large can be achieved (both with the light and the dark themes) changing the default orange to `#DB7500` and the default green to `#00A82D` (with the same hue, 100% saturation and maximum lightness).

> The Web Content Accessibility Guidelines were designed assuming a backlit computer screen, but Metropolis's primary use case is to be used on a projector. Do you know how these different viewing conditions affect the contrast ratio formula?

WCAG2.0 defines luminance contrast according to the standards ISO-9241-3 and ANSI-HFES-100-1988 as
`contrast = (L1+0.05)/(L2+0.05)`
where `L1`and `L2` are the relative luminances (not to be confused with lightness) of the brightest and the darkest color, respectively. Indeed, the relative luminance directly depends on the spectral power distribution of the illuminant (the reference white), but as far as I know for all calculations a standard illuminant (D65 for sRGB for example) is always assumed. This means that those contrast levels should be the same regardless of the illumination-viewing conditions.

**Comment by vitaminace33** [comment]
Hi, there! First, congrats for the theme. I've been using it since "beta".

The beamer I have is not really good so, in order to increase the contrast, I want to have the regular text in black, but I don't know how to do so. How can I set only the regular text in black? So far, the closest thing I have achieved is this:
```
\setbeamercolor{black text}{fg=black}
\setbeamercolor{block body}{use=black text, fg=black text.fg}
```
Cheers!

**Comment by alcarazr** [comment]
Please correct me if I'm wrong, but I'd say you just need to set:

`\setbeamercolor{normal text}{fg=black}`

Best,

**Comment by matze** [comment]
The alternative high contrast color scheme scores triple A but for the sake of keeping compatibility with existing user slides, I will keep the old the default. We can move towards a more legible version with a new major version.

**Comment by vitaminace33** [comment]
OMG, this is old. To set

\setbeamercolor{normal text}{fg=black}

does not the work. I found my own workaround but forgot to post it
here. I'll have a look into it.

Cheers,

Cédric M. Campos

------------------------------------------------------------

Sígueme en/Follow me at http://google.com/+cedricmartinezcampos

Por favor ten en cuenta el medio ambiente antes de imprimir este correo-e.
Please bear in mind the Environment before printing this email.
