### ISSUE TITLE
Highlights embedded links

### ISSUE THREAD

**Issue by anaderi** [matze/mtheme#24]
Hi! 
Was it an intention to make links indistinguishable from the plain text? Or can something beer done about it? Sometimes it worth making them underlined.

**Comment by matze** [comment]
Hmm, links should appear in *Fira Mono*. From the demo:

![mtheme-links](https://cloud.githubusercontent.com/assets/115270/5887748/8b9dd044-a3e2-11e4-82b8-995b18e6fbea.png)

**Comment by anaderi** [comment]
In case I put links inside \url{} they indeed made with Fira Mono. But if I use \href{}{}, they are just the same (look in the demo: 
\href{http://creativecommons.org/licenses/by-sa/4.0/}{Creative Commons
  Attribution-ShareAlike 4.0 International License}
). 
And if I use markdown + pandoc (which I really fond of), then mere links [text](http://url.com) are translated into href{URL}{TEXT}). 
Or am I missing something?

**Comment by matze** [comment]
Now I see. That is not caused by the theme but by the hyperref package. See [this answer](http://tex.stackexchange.com/a/202129/16394) on how to set the font for `\href`. You could probably renew the `\href` command to always show it in monospaced font but I doubt this is a good idea to set this in stone for the entire theme.

**Comment by anaderi** [comment]
ah, thanks! 
    \hypersetup{colorlinks=true,linkcolor=blue,urlcolor=blue}
did the trick
