### ISSUE TITLE
mtheme poster version

### ISSUE THREAD

**Issue by jpfairbanks** [matze/mtheme#297]
Hello @matze,

I really like this theme for slides, is there a poster version? If not, do you have a recommendation of a poster theme?

Thanks,
James

**Comment by matze** [comment]
Hi James, no there is no poster version of it. However, it should not be too hard to make it yourself because it's essentially just some color definitions and and font choice. By the way, I only ever made a poster once with LaTeX after that I just click them together in Inkscape … much saner for me ;-)

**Comment by jpfairbanks** [comment]
Thanks.
