### ISSUE TITLE
Support for subsections?

### ISSUE THREAD

**Issue by eddelbuettel** [matze/mtheme#53]
I am converting/updating some existing presentations of mine.  Longer ones have subsections.

Any views on whether 
+ having subsections is desirable
+ subsections should show the section they are in
+ subsections should show the progressbar?

My latex-fu is a little weak; I tried to hack a quick macro together but it didn't quite pan out.  Thoughts?

**Comment by matze** [comment]
*Disclaimer: this is purely subjective and my own opinion*

I never gave a talk longer than an hour and at least from my perspective just sections are usually enough to break up longer presentations. I know there is a tendency to break up a presentation into smaller topics if a theme encourage to do that (e.g. showing little dots and upcoming titles) but in my opinion this is just distracting and makes a presentation look very rigid.

Anyhow, I am not the one to decide how people structure their talks and in fact having smaller sections makes up for a nicer PDF table of contents. So here some thoughts:

> having subsections is desirable

As I said, people will agree or disagree :smile:

> subsections should show the section they are in

I would say so, otherwise it will probably just look like they are normal sections.

> subsections should show the progressbar?

I tend to say yes.

But it all boils down if you want to have subsections be handled like regular sections (i.e. with an inserted slide) or more subtle, for example by modifying the frametitle.

**Comment by eddelbuettel** [comment]
> I never gave a talk longer than an hour.

Lucky you :)   I am about to give a two-day workshop in a few weeks; I somewhat regularly do three-hour tutorials.   Subsections are nice to have.  I also work on a few shorter talks and for those _m_ is already perfect.

As for the longer format and use of `subsection`: Currently I get one typeset, but it does not "mesh" with the rest of the _m_ theme.  The font is one size smaller and there is no title bar.  So I'd like to do better.  Currently I can either comment out the subsection use (via `\AtBeginSection[]{}`) or live with the not-so-pretty one.  Thoughts?

**Comment by bgat** [comment]
I frequently give two-, three-, and four-day workshops.  Rather than use
subsections, I break my presentations up into individual files so that I'm
reminded to take breaks. It also lets me vary the order depending on
feedback during the event.

In my mind, subsections are evil...to the attendees.  :-)

b.g.


On Wed, May 20, 2015 at 7:11 AM, Dirk Eddelbuettel <notifications@github.com
> wrote:

> I never gave a talk longer than an hour.
>
> Lucky you :) I am about to give a two-day workshop in a few weeks; I
> somewhat regularly do three-hour tutorials. Subsections are nice to have. I
> also work on a few shorter talks and for those *m* is already perfect.
>
> As for the longer format and use of subsection: Currently I get one
> typeset, but it does not "mesh" with the rest of the *m* theme. The font
> is one size smaller and there is no title bar. So I'd like to do better.
> Currently I can either comment out the subsection use (via
> \AtBeginSection[]{}) or live with the not-so-pretty one. Thoughts?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/matze/mtheme/issues/53#issuecomment-103846038>.
>



-- 
Bill Gatliff
bgat@billgatliff.com

**Comment by bgat** [comment]
But, seriously...

Breaking my presentations up forces me to be more mindful about the
syllabus and presentation sequence so that each presentation file can stand
(mostly) on its own.  This tends to make me treat a topic more thoroughly
before I move on to the next one, which for my subject matter (embedded
Linux) is often a good thing.

Whenever I've dabbled with subsections, I've always ended up with a
presentation that is so spaghetti-like in its content, the flow just feels
wrong when I'm at the lectern.  I find myself thinking, "what were we
talking about, again?" a lot.

I'm not saying subsections are objectively evil, I'm just saying that in my
cases they've masked other problems.  Your mileage may vary, especially if
you have any formal training in public speaking (I don't).

b.g.


On Wed, May 20, 2015 at 7:25 AM, Bill Gatliff <bgat@billgatliff.com> wrote:

> I frequently give two-, three-, and four-day workshops.  Rather than use
> subsections, I break my presentations up into individual files so that I'm
> reminded to take breaks. It also lets me vary the order depending on
> feedback during the event.
>
> In my mind, subsections are evil...to the attendees.  :-)
>
> b.g.
>
>
> On Wed, May 20, 2015 at 7:11 AM, Dirk Eddelbuettel <
> notifications@github.com> wrote:
>
>> I never gave a talk longer than an hour.
>>
>> Lucky you :) I am about to give a two-day workshop in a few weeks; I
>> somewhat regularly do three-hour tutorials. Subsections are nice to have. I
>> also work on a few shorter talks and for those *m* is already perfect.
>>
>> As for the longer format and use of subsection: Currently I get one
>> typeset, but it does not "mesh" with the rest of the *m* theme. The font
>> is one size smaller and there is no title bar. So I'd like to do better.
>> Currently I can either comment out the subsection use (via
>> \AtBeginSection[]{}) or live with the not-so-pretty one. Thoughts?
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/matze/mtheme/issues/53#issuecomment-103846038>.
>>
>
>
>
> --
> Bill Gatliff
> bgat@billgatliff.com
>



-- 
Bill Gatliff
bgat@billgatliff.com

**Comment by eddelbuettel** [comment]
Ok, now that we are done lecturing me about how childish all this is, can we get back to recognizing that _bascially all other beamer themes support subsections_ and that the choice, just maybe, ought to reside with the presentation author?

**Comment by bgat** [comment]
On Wed, May 20, 2015 at 7:36 AM, Dirk Eddelbuettel <notifications@github.com
> wrote:

> Ok, now that we are done lecturing me about how childish all this is, can
> we get back to recognizing that *bascially all other beamer themes
> support subsections* and that the choice, just maybe, ought to reside
> with the presentation author?
>

But where's the fun in that?  :-)

Seriously, the minimalism of mtheme might not accommodate multiple levels
of sectioning without breaking it.  I'm thinking about the progress bar in
particular: do you want it to show progress through the section, or through
the whole document? And whatever answer you pick, someone else will pick
the other one.

If Tufte were dead, he might be rolling in his grave at this point.

Subsections seem to me to be more like an editorial device than a
presentation device.  The reason other beamer themes support them is
because those themes seem (to me) to be mere visualizations of a document
structure, which doesn't really help when presenting the material contained
in that document.

Put another way: if you have subsections, you might have just written a
document/thesis rather than a presentation.  If that's the case, then
you've got to admit that your "presentation" is just standing at the front
of the room reading the document, rather than conveying the essential
concepts that the document also describes.  If that's your thing, then I
can see how subsections are useful to you---but in that case, mtheme might
not be.

I view mtheme as a theme that's been reduced to the essence of
presentation, by eliminating everything else including the notion of
"document".  It's also a nice color palette and symbol set.  The notion of
"section" in mtheme to me represents a shift in topic that is better
handled by a visual break in the flow, rather than a slide with prose that
serves as a segue.  It's a visual version of, "and now, for something
[almost completely] different...".

To me, when you're asking for subsection support in mtheme, you're first
asking for the addition of a concept of "section" that's fundamentally
different from the one that mtheme offers.


b.g.
-- 
Bill Gatliff
bgat@billgatliff.com

**Comment by eddelbuettel** [comment]
Can  you please stop?

**Comment by rchurchley** [comment]
I share @matze's opinion. I personally don't use subsections, but I'm not one to dictate how people give talks. I don't think @eddelbuettel's request is unreasonable at all. If someone delivers a multi-day workshop consisting essentially of a series of related talks, I think it should be their call as to whether to organize those talks in one document file or several.

I would suggest that @eddelbuettel might want to use `\part` and `\section` to divide his talks up instead of `\section` and `\subsection` — that's what the beamer documentation recommends. However, this only shifts the problem, since the mtheme doesn't support `\part` either.

I am almost finished a "refactor" of the sectioning and progress bar code that would make it easy to implement \subsectionpage et al. Once I'm finished that, I'll propose some designs here.

**Comment by rchurchley** [comment]
Incidentally, @bgat, I think you mean your comments in jest but in writing your tone is coming across as unnecessarily antagonistic. There's no need to bury and rotate Tufte just because someone wants to concatenate their presentation files!

**Comment by eddelbuettel** [comment]
Oh, gosh, something constructive. Must be the wrong thread :)    My thanks to @rchurchley for restoring some sanity.

On the (short-ish) morning train I started a local branch basically copying what section down to subsection. It didn't quite work yet but I try again...  I am quite sympathetic to the idea of using part [1] and section, though it does in fact just move the goal posts around as @rchurchley notes.  

[1] Though possibly the documents I ever used `\part{}` where my dissertation back-then-when and the more recent book...

**Comment by bgat** [comment]
Guys:


I apologize for the antagonistic tone, and I certainly didn't mean to "bury
and rotate" anyone.  :-)  While my writing style can sometimes be harsh, I
assure you that in person I'm really a pretty nice guy.  :-)  I guess that
in my aim for clarity in what I'm trying to say, I sometimes end up with
sharp edges where I don't really mean them.  Please accept my apologies.

Humor me for just one more second, though?

The point I was (poorly) attempting to make was that while it might _seem_
like it's entirely up to the presenter to decide whether or not to use
subsections et. al during the delivery of their material, in truth (I
think) the best answer actually lies with the audience.  And I've observed
that when I'm listening to a presentation, subsections add a layer of
structure that's distracting from the content itself: if you're going to
talk about something, then talk about it...and then talk about what's
clearly the next most important thing, based on what you've just told the
listener is the next most important thing.

If the sequence and structure of the presentation material doesn't
naturally, cognitively lead the listener from one topic to the next, then
subsections don't really fix that problem.  You'll create a better
presentation if you reorder the material, or refine the delivery of it, so
that you don't _need_ subsections.  The audience can hear only one thing at
a time, anyway.

Let's say I'm giving a presentation that teaches the listener what a "tree"
is.  I may tell them in the beginning that I'm starting at the top and
working downwards, and then I'll explain the leaves, and then branches, and
then the trunk and roots.  They won't have any problem following along
because I gave them the cognitive structure of the material up front.

I may then tell them I'm going "inwards", slicing into the trunk to explain
the various layers that most tree trunks have: bark, cambium, sapwood,
heartwood, and then pith at the very center.  Yes, those are "hierarchical"
layers, and a scientist would obviously document them as such...but you
don't organize your presentation that way.  Instead, a listener is going to
want you to explain "bark", and then "cambium", and then "sapwood", and so
on, as standalone topics.  Sections, not subsections.

When you casually describe the parts of a tree trunk to someone, it isn't
"trunk-bark", "trunk-bark-cambium", and then "trunk-bark-cambium-sapwood";
and, it isn't "tree-trunk", "tree-bark", "tree-cambium", either... it's
just "bark", "cambium", and so on.  There's no notion of subsection.

Documents need subsections, without question.  I don't think presentations
benefit from them at all.

That's the point that I was trying to make.  I'm (overly, perhaps)
passionate about this stuff, because I'm eaten alive with ADHD and
observations like the above are the only way I can stay on task as a
listener OR a presenter.

But, I'm no expert...and I'm willing to admit I'm wrong if I am, and I'm
definitely open to suggestions for improvement.

I'll drop the issue now, because even if mtheme ends up adding support for
subsections, I won't use them.  So, I really shouldn't have bothered to get
into this thread at all.  Oops.  :-)


b.g.




On Wed, May 20, 2015 at 1:21 PM, Ross Churchley <notifications@github.com>
wrote:

> Incidentally, @bgat <https://github.com/bgat>, I think you mean your
> comments in jest but in writing your tone is coming across as unnecessarily
> antagonistic. There's no need to bury and rotate Tufte just because someone
> wants to concatenate their presentation files!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/matze/mtheme/issues/53#issuecomment-103966857>.
>



-- 
Bill Gatliff
bgat@billgatliff.com

**Comment by eddelbuettel** [comment]
I now have a minimal working example in [this branch of my fork of mtheme](https://github.com/eddelbuettel/mtheme/tree/feature/subsections).

**Comment by rchurchley** [comment]
I've submitted a pull request containing greatly simplified progress bar and section code, and it should be considerably easier to create a `part page` or `subsection page` from it.

**Comment by eddelbuettel** [comment]
:+1:

**Comment by matze** [comment]
I am not going to heat up the argument once more but I have to defend @bgat a bit in that a more organic flow probably helps keeping awake than a overly hierarchic structure. But let's draw the line about that discussion here :smile:

---

As soon as @rchurchley's PR is polished and through we can discuss how to proceed with subsections. As far as I can see the PR does not address the presentation of subsections but provides the groundwork to implement them.
